name: AfkManager
main: com.douglas_srs.AfkManager.AfkManager
version: 2.0.1
website: http://www.mestrecraft.com.br/threads/afkmanager.18/
description: Manage AFK players!
author: douglas_srs
depend: [Vault]

commands:
    afkmanager:
        description: Reloads the configuration from file.
        usage: /<command> reload
        aliases: am

permissions:
    afkmanager.exempt:
        description: Don't get kicked by AfkManager
        default: op