name: AfkManager
main: com.douglas_srs.AfkManager.AfkManager
version: 1.4
website: http://www.mestrecraft.com.br/
description: Manage AFK players!
author: douglas_srs

commands:
    afkmanager:
        description: Reloads the configuration from file.
        usage: /<command> reload
        aliases: am
depend: [Vault]

permissions:
    afkmanager.exempt:
        description: Don't get kicked by AfkManager
        default: op